name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy bootstrap config
      run: |
        aws s3 sync ./bootstrap-4.env s3://bootstrap-peerchecker-com-dist --delete
        aws cloudfront create-invalidation --distribution-id ETKLQVXX2I9CQ --paths '/*';